Use case apt application
TBD54566975/ssi-sdk pull request #164
Opened 2022-08-09 22:17 UTC by nitro-neal

This is a full example flow of an apartment verifying the age of a potential tenant.

2022-08-09 22:30 UTC, decentralgabe requested changes
mostly small comments. looks great.

2022-08-09 22:30 UTC, decentralgabe commented on example/use_cases/apartment_application/apartment_application.go
> +	holderDIDPrivateKey, holderDIDKey, _ := did.GenerateDIDKey(crypto.Ed25519)
the other examples do some light error handling like this, what do you think? https://github.com/TBD54566975/ssi-sdk/blob/main/example/vc/vc.go#L54

2022-08-09 22:30 UTC, decentralgabe commented on example/use_cases/apartment_application/apartment_application.go
> +	govtDidPrivateKey, govtDIDKey, _ := did.GenerateDIDKey(crypto.Ed25519)
```suggestion
	govtDIDPrivateKey, govtDIDKey, _ := did.GenerateDIDKey(crypto.Ed25519)
```

2022-08-09 22:30 UTC, decentralgabe commented on example/use_cases/apartment_application/apartment_application.go
> +	govtJWK, _ := cryptosuite.JSONWebKey2020FromEd25519(govtDidPrivateKey.(ed25519.PrivateKey))
```suggestion
	govtJWK, _ := cryptosuite.JSONWebKey2020FromEd25519(govtDIDPrivateKey.(ed25519.PrivateKey))
```

2022-08-09 22:30 UTC, decentralgabe commented on example/use_cases/apartment_application/apartment_application.go
> +		 Step 2: Government issuer issues credentials to holder claiming age. The government issuer then signs the verifiable credentials to holder claiming age
nit: `issuer issues a credential to the holder providing their age. The government...`

2022-08-09 22:30 UTC, decentralgabe commented on example/use_cases/apartment_application/apartment_application.go
> +	assert.NoError(nil, vc.IsValid())
no assertions in non-test files 😄

2022-08-09 22:30 UTC, decentralgabe commented on example/use_cases/apartment_application/apartment_application.go
> +		Step 3: Create presentation definition from the apartment to the holder which goes into a presentation request.
maybe language fix to make it clear that the physical apartment building is not making the request 😉

2022-08-09 22:30 UTC, decentralgabe commented on example/use_cases/apartment_application/apartment_application.go
> +	assert.NoError(nil, presentationDefinition.IsValid())
remove

2022-08-09 22:30 UTC, decentralgabe commented on example/use_cases/apartment_application/apartment_application.go
> +	// TODO: Have the presentation claim's token format support signedVCBytes for the BuildPresentationSubmission function
nit: for TODOs, generally advisable to link to an issue (or at least create one). I know I haven't been great about this either.

2022-08-10 15:59 UTC, decentralgabe commented on example/use_cases/apartment_application/apartment_application.go
>  	holderVerifier, _ := cryptosuite.NewJSONWebKeyVerifier(holderJWK.ID, holderJWK.PublicKeyJWK)
these should have err checks as well and all else below 😄

2022-08-15 16:48 UTC, decentralgabe approved these changes
excellent work!

2022-08-15 16:55 UTC, nitro-neal commented
<img width="833" alt="image" src="https://user-images.githubusercontent.com/5314059/184679946-ba5336ae-365a-46fd-9d18-05cc76832edf.png">

2022-08-15 16:59 UTC, merged